<?xml version="1.0" encoding="UTF-8"?><record_update table="sys_script_include">
    <sys_script_include action="INSERT_OR_UPDATE">
        <access>public</access>
        <active>true</active>
        <api_name>x_snc_doom.LogError</api_name>
        <caller_access>1</caller_access>
        <client_callable>false</client_callable>
        <description>Produces an error log output in the application log.</description>
        <mobile_callable>false</mobile_callable>
        <name>LogError</name>
        <sandbox_callable>false</sandbox_callable>
        <script><![CDATA[function LogError(vPayload)
{
	gs.error(x_snc_devtools.PrepareLogError(vPayload));
}]]></script>
        <sys_class_name>sys_script_include</sys_class_name>
        <sys_created_by>admin</sys_created_by>
        <sys_created_on>2025-05-09 14:11:20</sys_created_on>
        <sys_id>c8d0aa579351a610ae97b4aa6aba1083</sys_id>
        <sys_mod_count>0</sys_mod_count>
        <sys_name>LogError</sys_name>
        <sys_package display_value="Doom" source="x_snc_doom">fd8c8ddb931d6610ae97b4aa6aba1095</sys_package>
        <sys_policy/>
        <sys_scope display_value="Doom">fd8c8ddb931d6610ae97b4aa6aba1095</sys_scope>
        <sys_update_name>sys_script_include_c8d0aa579351a610ae97b4aa6aba1083</sys_update_name>
        <sys_updated_by>admin</sys_updated_by>
        <sys_updated_on>2025-05-09 14:11:20</sys_updated_on>
    </sys_script_include>
</record_update>
